@extends('frontend.template')
@section('title')
About
@endsection
@section('content')	
    <div class="main">
    <div class="content">
	<!---728x90--->

    	<div class="section group">
				<div class="col_1_of_3 span_1_of_3">
					<h3>Who We Are</h3>
					<img src="{{asset('public/frontend/images/about_img.jpg')}}" alt="">
					<p>FPL Limited is committed to manufacturing the highest quality plastic goods. Our engineers offer a multitude of benefits and value-added services to our customers. Our plastic items are engineered for uncompromising performance and long-lasting operation. We have been manufacturing high quality Plastic goods since one year and we are eager to assist any customer with their plastic needs. The plastic industry is consistently changing as the demands for plastics evolve. Customers have a variety of suppliers to choose from and many turn to Polytec Plastics FPL ltd. for a variety of plastic channels, profiles and more.</p>
					<p>The engineers at FPL Limited develop our premier plastic solutions to offer superior flexibility or sturdiness based on the needs of our customers. Our plastic profiles can be extruded up to 1.5" litter and all of these solutions are Q-1 certified. If any customers require design assistance then the staff at FPL Limited can easily work with our customers to develop the most beneficial plan to manufacture items. Our company can design your plastic products from a simple hand sketch or a CAD file. Just let our engineers know what you are looking for and we will assist you!.</p>
				</div>
				<div class="col_1_of_3 span_1_of_3">
					<h3>Our History</h3>
				 <div class="history-desc">
				 		<strong style="color:#E4292F; font-weight: bolder;">Purpose :</strong>
					<!-- <div class="year"><p> purpose:</p></div> -->
					<p class="history">Creating sustainable value.</p>
				 <div class="clear"></div>
				</div>
				 <div class="history-desc">
				 	
				 	<strong style="color:#E4292F; font-weight: bolder;"> Vision :</strong>
					<!-- <div class="year"><p> Vision</p></div> -->
					<p class="history">Leading with our innovations, brands and technologies.</p>
				 <div class="clear"></div>
				</div>
				 <div class="history-desc">
				 	
				 		<strong style="color:#E4292F; font-weight: bolder;">Mission :</strong>
					<!-- <div class="year"><p>mission</p></div> -->
					<p class="history">We want to serve our customers and consumers worldwide as the most trusted partner with leading positions in all relevant markets and categories – as a passionate team united by shared values.</p>
				 <div class="clear"></div>
				</div>
			
				<div class="history-desc">
					<strong style="color:#E4292F; font-weight: bolder;">Challenge”, “Communication”, and “Creation:</strong>				
					<p class="history">is the FPL Limited most essential motto. We all know that our growth can not be achieved without “Creation”. 
This “Creation” is produced by teamwork, which is generated by continuous “Challenge” and “Communication” “FPL Limited growing with these three motto.</p>
				 <div class="clear"></div>
				</div>
				<div class="history-desc">
					<strong style="color:#E4292F; font-weight: bolder;">Quality Policy:</strong>				
					<p class="history">To achieve customer delight by manufacturing products as per customer specification and on - time delivery of good quality products at competitive price through continuous improvement at all levels</p>
				 <div class="clear"></div>
				</div>
				<div class="history-desc">
					<strong style="color:#E4292F; font-weight: bolder;">Strengths:</strong>				
					<p class="history">Business is people. Business never goes well without them. In a same way, people never find jobs without job opportunity. We create job opportunity. We create opportunity for people to glow themselves. That is what we believe the most important responsibility to society</p>
				 <div class="clear"></div>
				</div>
				<div class="history-desc">
					<strong style="color:#E4292F; font-weight: bolder;">Human Resource:</strong>				
					<p class="history">Goodwill in the international market, Cost effective, On-time delivery, Safe packing, Customized solutions</p>
				 <div class="clear"></div>
				</div>
			</div>
				<div class="col_1_of_3 span_1_of_3">				

					<h3>Products</h3>

					<div class="history-desc">
					<strong style="color:#E4292F; font-weight: bolder;">Products:</strong>				
					<p class="history">FPL Limited Plastics is dedicated to manufacturing high quality blow-molded plastic products like Ovals, Spice, Cylinder, Canisters, Decanter and Carafe, Modern Rour, Serum, Alcohol.
</p>
					 <div class="clear"></div>
					</div>

					<div class="history-desc">
					<strong style="color:#E4292F; font-weight: bolder;">Capabilities:</strong>				
					<p class="history"> We here at FPL Limited, produce a wide range of blow- molded bottles, containers and specialty parts in size ranging from 5 ml to 1,500 ml bottle capacity. High quality output for HDPE, LDPE, PP and CPP materials.</p>
					 <div class="clear"></div>
					</div>

					<div class="history-desc">
					<!-- <strong style="color:#E4292F; font-weight: bolder;">Products:</strong>				 -->
					<p class="history"><strong style="font-weight:600;">Our skilled and experienced team can help bring your packaging ideas to life. Whether your project involves unique shapes, specialized features, innovative finishes – or just about anything else you can dream up, we'll work with you to develop an economical solution that meets your objectives and needs.</strong>

</p>
					 <div class="clear"></div>
					</div>

					<p>FPL Limited is dedicated to manufacturing high quality blow-molded plastic products, providing timely deliveries and creating an atmosphere of continuous improvements where all employees strive to keep both internal and external customers satisfied.</p>
				   
					 <p>FPL Limited understands that in today’s Bangladesh you are looking for a company that is knowledgeable within your industry, provides excellent service and high standards of quality products. Our team will work with you from inception throughout the lifetime of your project.</p>
				</div>
			</div>			
    </div>
 </div>
</div>
</div>
    @endsection